@startuml
'https://plantuml.com/sequence-diagram

title message存储：<color red>标红为核心逻辑 <color green> 绿色：后续待补充
'自动对消息编号
autonumber
'自动激活关键字
autoactivate on
'设置间距
'skinparam ParticipantPadding 5
skinparam BoxPadding 20

actor mq消息

box store
participant CommitLog
participant MappedFileQueue
participant MappedFile
end box

mq消息 -> CommitLog: putMessage
note  right
位置：org.apache.rocketmq.store.CommitLog.putMessage
end note

CommitLog -> MappedFileQueue: <color red>getLastMappedFile
return MappedFile

note  right
逻辑：获取待写入映射文件
- CopyOnWriteArrayList<MappedFile> mappedFiles
- org.apache.rocketmq.broker.BrokerController.initialize (BrokerStartup 启动时初始化写入映射文件：mappedFiles)
end note

CommitLog -> CommitLog: <color red>lock

note  right
逻辑：本地锁
ReentrantLock putMessageNormalLock = new ReentrantLock()
putMessageNormalLock.lock()
end note
return

CommitLog -> MappedFile: appendMessage
MappedFile -> CommitLog: <color red>doAppend

note  right
消息写入缓冲区（ByteBuffer）
位置：org.apache.rocketmq.store.MappedFile.writeBuffer
end note
return AppendMessageResult
return AppendMessageResult
CommitLog -> CommitLog: <color red>unlock
return
note  right
本地锁解锁
end note
CommitLog -> CommitLog: <color red>handleDiskFlush
note  right
同步刷盘或异步刷盘-todo 待了解清楚
1、org.apache.rocketmq.broker.BrokerStartup.createBrokerController； 实例化：flushCommitLogService = new GroupCommitService()
2、org.apache.rocketmq.broker.BrokerStartup.start broker启动时(flushCommitLogService.start()) 根据配置文件,开启同步刷盘线程
end note
CommitLog -> CommitLog: putRequest
note  right
1、List<GroupCommitRequest> requestsWrite
2、requestsWrite.add(request) 添加请求 （GroupCommitRequest 代表刷盘的一个请求）
3、flushCommitLogService 线程内while 循环处理请求
 - waitForRunning 读写分离 （org.apache.rocketmq.store.CommitLog.GroupCommitService.swapRequests）
end note
CommitLog -> MappedFileQueue: flush
MappedFileQueue -> MappedFileQueue: findMappedFileByOffset()
note  right
逻辑：根据offset 获取映射文件
end note
return MappedFile
MappedFileQueue -> MappedFile: flush
note  right
1、org.apache.rocketmq.store.MappedFile.fileChannel
2、fileChannel.force ｜｜ mappedByteBuffer.force()
end note
@enduml